#include <libfprint-2/fprint.h>

// Manually declare missing types that GObject macros generate
typedef struct _FpContextClass FpContextClass;
typedef struct _FpDeviceClass FpDeviceClass;
typedef FpPrint *FpPrint_autoptr;

// Declare the _get_type functions that are generated by G_DECLARE_DERIVABLE_TYPE
GType fp_context_get_type(void);
GType fp_device_get_type(void);
GType fp_image_get_type(void);
GType fp_print_get_type(void);
